name: Deploy to GitHub Pages

on:
  push:
    branches: [ main, master ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: npm run build
        env:
          GOOGLE_MAPS_API_KEY: "AIzaSyBPIV6dI_r3YEPEIqVNpeG_h2YuuaYyShI"
          GOOGLE_MAPS_PLATFORM_KEY: "AIzaSyBPIV6dI_r3YEPEIqVNpeG_h2YuuaYyShI"
          GEMINI_API_KEY: "AIzaSyD6nouZHMjcIET5xPY08VXFoXYoA9_4BWk"
          APP_URL: "https://ais-dev-2rtc2gfigfd453ntskkeah-155701770735.europe-west2.run.app"
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
